export const ipcChannels = {
  settingsGet: 'settings.get',
  settingsSave: 'settings.save',
  settingsTestConnection: 'settings.testConnection',
  booksImportMarkdown: 'books.importMarkdown',
  booksImportEpub: 'books.importEpub',
  booksList: 'books.list',
  booksOpen: 'books.open',
  aiRunReadingAction: 'ai.runReadingAction',
  aiFollowUp: 'ai.followUp',
  aiStream: 'ai.stream',
  threadsListByBook: 'threads.listByBook',
  threadsListWithMessagesByBook: 'threads.listWithMessagesByBook',
  booksSetActiveThread: 'books.setActiveThread',
  booksSetContextStrategy: 'books.setContextStrategy',
} as const;
