export const ipcChannels = {
  settingsGet: 'settings.get',
  settingsSave: 'settings.save',
  settingsTestConnection: 'settings.testConnection',
  booksImportFiles: 'books.importFiles',
  booksList: 'books.list',
  booksOpen: 'books.open',
  aiCreateConversation: 'ai.createConversation',
  aiFollowUp: 'ai.followUp',
  aiRetry: 'ai.retry',
  aiStream: 'ai.stream',
  threadsListByBook: 'threads.listByBook',
  threadsListWithMessagesByBook: 'threads.listWithMessagesByBook',
  threadsDelete: 'threads.delete',
  booksSetActiveThread: 'books.setActiveThread',
  booksSetContextStrategy: 'books.setContextStrategy',
  shellOpenExternal: 'shell.openExternal',
} as const;
